#!/usr/bin/env python3
"""Render PrometheusRule CRDs into plain Prometheus rule files.

`promtool` understands a rule file — a document with a top-level `groups` key.
What lives in this repository is a `PrometheusRule` custom resource, where the
same content sits under `spec`. Everything downstream (promtool check, promtool
test, any linter) needs the unwrapped form, so unwrapping happens once, here.

    ./scripts/render-rules.py                 # alerts/*.yaml -> .rendered/
    ./scripts/render-rules.py --check         # verify only, write nothing

Stdlib plus PyYAML; no cluster and no network.
"""

from __future__ import annotations

import argparse
import pathlib
import sys

import yaml

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
DEFAULT_SOURCE = REPO_ROOT / "alerts"
DEFAULT_OUTPUT = REPO_ROOT / ".rendered"


class RenderError(RuntimeError):
    """A source document is not a usable PrometheusRule."""


def unwrap(document: dict, source: pathlib.Path) -> dict:
    """Return the plain rule-file body of a PrometheusRule document."""
    if not isinstance(document, dict):
        raise RenderError(f"{source}: not a YAML mapping")

    kind = document.get("kind")
    if kind != "PrometheusRule":
        raise RenderError(f"{source}: expected kind PrometheusRule, found {kind!r}")

    spec = document.get("spec")
    if not isinstance(spec, dict) or "groups" not in spec:
        raise RenderError(f"{source}: spec.groups is missing")

    groups = spec["groups"]
    if not isinstance(groups, list) or not groups:
        raise RenderError(f"{source}: spec.groups is empty")

    for group in groups:
        if not isinstance(group, dict) or not group.get("name"):
            raise RenderError(f"{source}: a rule group has no name")
        if not group.get("rules"):
            raise RenderError(f"{source}: group {group.get('name')!r} has no rules")

    return {"groups": groups}


def render(source_dir: pathlib.Path, output_dir: pathlib.Path,
           check_only: bool = False) -> list[pathlib.Path]:
    """Render every PrometheusRule in source_dir. Returns the output paths."""
    sources = sorted(source_dir.glob("*.yaml")) + sorted(source_dir.glob("*.yml"))
    if not sources:
        raise RenderError(f"no YAML files found in {source_dir}")

    if not check_only:
        output_dir.mkdir(parents=True, exist_ok=True)

    written: list[pathlib.Path] = []
    for source in sources:
        document = yaml.safe_load(source.read_text(encoding="utf-8"))
        body = unwrap(document, source)

        target = output_dir / source.name
        if not check_only:
            target.write_text(
                "# Generated by scripts/render-rules.py — do not edit.\n"
                + yaml.safe_dump(body, sort_keys=False, width=10_000),
                encoding="utf-8",
            )
        written.append(target)

    return written


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--source", type=pathlib.Path, default=DEFAULT_SOURCE,
                        help="directory holding PrometheusRule manifests")
    parser.add_argument("--output", type=pathlib.Path, default=DEFAULT_OUTPUT,
                        help="directory to write plain rule files into")
    parser.add_argument("--check", action="store_true",
                        help="validate the manifests without writing anything")
    args = parser.parse_args(argv)

    try:
        written = render(args.source, args.output, check_only=args.check)
    except RenderError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    except yaml.YAMLError as exc:
        print(f"error: invalid YAML: {exc}", file=sys.stderr)
        return 1

    verb = "checked" if args.check else "rendered"
    for path in written:
        print(f"{verb} {path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
